Use static analysis in blocking mode (#16)
* Fail if clang-tidy found warnings
* Fail if PVS-Studio found warnings
* Use clang as a compiler on Ubuntu
* Build qtbase and qttools from source on Ubuntu and MacOS to fix C++20 compatibility

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -13,6 +13,9 @@ jobs:
       BOOST_INSTALL_PATH: boost-install
       CYRUS_SASL_VERSION: 2.1.27
       CYRUS_SASL_INSTALL_PATH: cyrus-sasl-install
+      QT_SHORT_VERSION: 5.15
+      QT_VERSION: 5.15.1
+      QT_INSTALL_PATH: qt-install
     strategy:
       fail-fast: true
       matrix:
@@ -23,9 +26,9 @@ jobs:
             build_type: "Release", cc: "gcc", cxx: "g++",
           }
         - {
-            name: "Ubuntu Latest GCC", artifact: "Linux",
+            name: "Ubuntu Latest Clang", artifact: "Linux",
             os: ubuntu-20.04,
-            build_type: "Release", cc: "gcc", cxx: "g++",
+            build_type: "Release", cc: "clang", cxx: "clang++",
           }
         - {
             name: "MacOS Latest Clang", artifact: "MacOS",
@@ -45,7 +48,7 @@ jobs:
         with open(os.environ['GITHUB_ENV'], 'a') as env_file:
           env_file.write("REPO_PATH={}\n".format(repo.replace("\\", "\\\\")))
           env_file.write("ROOT_PATH={}\n".format(root.replace("\\", "\\\\")))
-    
+
     - name: Install required python modules
       run: pip install requests
 
@@ -53,28 +56,28 @@ jobs:
       if: ${{ matrix.config.name == 'Windows Latest MinGW64' }}
       shell: C:\\msys64\\msys2_shell.cmd -defterm -no-start -mingw64 -shell sh {0}
       run: |
-        # Comment because gcc and cmake are already installed 
-        # pacman -S --noconfirm mingw-w64-x86_64-gcc 
+        # Comment because gcc and cmake are already installed
+        # pacman -S --noconfirm mingw-w64-x86_64-gcc
         # pacman -S --noconfirm mingw-w64-x86_64-cmake
         pacman -S --noconfirm mingw-w64-x86_64-ninja
-        
+
     - name: Install build tools (Ubuntu)
-      if: ${{ matrix.config.name == 'Ubuntu Latest GCC' }}
+      if: ${{ matrix.config.name == 'Ubuntu Latest Clang' }}
       shell: sh {0}
       run: |
-        # Comment because cmake is already installed 
+        # Comment because cmake is already installed
         # apt-get install cmake -y
-        sudo apt-get install gcc-9 g++-9 -y
+        sudo apt-get install clang -y
         sudo apt-get install ninja-build -y
-        
+
     - name: Install build tools (MacOS)
       if: ${{ matrix.config.name == 'MacOS Latest Clang' }}
       shell: sh {0}
       run: |
-        # Comment because cmake is already installed 
+        # Comment because cmake is already installed
         # brew install cmake
         brew install ninja
-        
+
     - name: Boost cache
       uses: actions/cache@v2
       id: cache_boost
@@ -116,10 +119,10 @@ jobs:
 
         os.chdir(boost_source_dir)
 
-        if "${{ matrix.config.name }}" == "Windows Latest MinGW64" or \
-           "${{ matrix.config.name }}" == "Ubuntu Latest GCC":
+        if "${{ matrix.config.name }}" == "Windows Latest MinGW64":
           toolset = "gcc"
-        elif "${{ matrix.config.name }}" == "MacOS Latest Clang":
+        elif "${{ matrix.config.name }}" == "MacOS Latest Clang" or
+             "${{ matrix.config.name }}" == "Ubuntu Latest Clang":
           toolset = "clang"
         else:
           raise RuntimeError("Unknown config name {}".format("${{ matrix.config.name }}"))
@@ -137,26 +140,28 @@ jobs:
           execute_command("./bootstrap.sh --with-libraries=program_options,system --with-toolset={} --prefix={}".format(toolset, boost_install_dir))
           execute_command("./b2")
           execute_command("./b2 install")
-      
+
         os.chdir(repo)
-    
+
     - name: Cyrus SASL (Windows)
       if: ${{ matrix.config.name == 'Windows Latest MinGW64' }}
       shell: C:\\msys64\\msys2_shell.cmd -defterm -no-start -mingw64 -shell sh {0}
       run: |
         pacman -S --noconfirm mingw-w64-x86_64-cyrus-sasl
-    
+
     - name: Cyrus SASL cache (Ubuntu & MacOS)
       uses: actions/cache@v2
-      if: ${{ matrix.config.name == 'Ubuntu Latest GCC' || matrix.config.name == 'MacOS Latest Clang' }}
+      if: ${{ matrix.config.name == 'Ubuntu Latest Clang' || matrix.config.name == 'MacOS Latest Clang' }}
       id: cache_cyrus_sasl_unix
       with:
         path: ${{ env.ROOT_PATH }}/cyrus-sasl-install
         key: ${{ runner.os }}-cyrus-sasl-${{ env.CYRUS_SASL_VERSION }}
-    
+
     - name: Cyrus SASL (Ubuntu & MacOS)
-      if: ${{ (matrix.config.name == 'Ubuntu Latest GCC' || matrix.config.name == 'MacOS Latest Clang') && steps.cache_cyrus_sasl_unix.outputs.cache-hit != 'true' }}
-      id: cyrus_sasl_unix
+      if: ${{ (matrix.config.name == 'Ubuntu Latest Clang' || matrix.config.name == 'MacOS Latest Clang') && steps.cache_cyrus_sasl_unix.outputs.cache-hit != 'true' }}
+      env:
+        CC: ${{ matrix.config.cc }}
+        CXX: ${{ matrix.config.cxx }}
       shell: python {0}
       run: |
         import os
@@ -174,7 +179,7 @@ jobs:
         os.chdir(root)
 
         sasl_version = os.environ['CYRUS_SASL_VERSION']
-        
+
         sasl_source_dir  = os.path.normpath(os.path.join(root, "cyrus-sasl-{}".format(sasl_version)))
         sasl_install_dir = os.path.normpath(os.path.join(root, "${{ env.CYRUS_SASL_INSTALL_PATH }}"))
         os.mkdir(sasl_install_dir)
@@ -188,28 +193,78 @@ jobs:
         execute_command("chmod +x ./configure")
         execute_command("./configure --prefix={}".format(sasl_install_dir))
         execute_command("chmod +x ./config/install-sh")
-        execute_command("make")
+        execute_command("make -j2")
         execute_command("sudo make install")  # MacOS requires sudo to copy files to /Library/Frameworks/
         os.chdir(repo)
-    
+
     - name: Qt5 (Windows)
       if: ${{ matrix.config.name == 'Windows Latest MinGW64' }}
       shell: C:\\msys64\\msys2_shell.cmd -defterm -no-start -mingw64 -shell sh {0}
       run: |
         pacman -S --noconfirm mingw-w64-x86_64-qt5
-        
-    - name: Qt5 (Ubuntu)
-      if: ${{ matrix.config.name == 'Ubuntu Latest GCC' }}
-      shell: sh {0}
+
+    - name: Qt5 cache (Ubuntu & MacOS)
+      uses: actions/cache@v2
+      if: ${{ matrix.config.name == 'Ubuntu Latest Clang' || matrix.config.name == 'MacOS Latest Clang' }}
+      id: cache_qt_unix
+      with:
+        path: ${{ env.ROOT_PATH }}/qt-install
+        key: ${{ runner.os }}-qt-qtbase-qttools-${{ env.QT_VERSION }}
+
+    - name: Qt5 (Ubuntu & MacOS)
+      if: ${{ (matrix.config.name == 'Ubuntu Latest Clang' || matrix.config.name == 'MacOS Latest Clang') && steps.cache_qt_unix.outputs.cache-hit != 'true' }}
+      env:
+        CC: ${{ matrix.config.cc }}
+        CXX: ${{ matrix.config.cxx }}
+      shell: python {0}
       run: |
-        sudo apt-get install qt5-default qttools5-dev -y
-        
-    - name: Qt5 (MacOS)
-      if: ${{ matrix.config.name == 'MacOS Latest Clang' }}
-      shell: sh {0}
-      run: |
-        brew install qt5
-    
+        import os
+        import requests
+        import subprocess
+
+        def execute_command(cmd):
+          ret = subprocess.call(cmd, shell=True)
+          if ret != 0:
+            raise RuntimeError('Exit code {} while executing "{}"'.format(ret, cmd))
+
+        root = os.environ['ROOT_PATH']
+        repo = os.environ['REPO_PATH']
+
+        os.chdir(root)
+
+        qt_install_dir = os.path.normpath(os.path.join(root, "${{ env.QT_INSTALL_PATH }}"))
+        os.mkdir(qt_install_dir)
+
+        qt_short_version = os.environ['QT_SHORT_VERSION']
+        qt_version = os.environ['QT_VERSION']
+
+        qtbase_source_dir  = os.path.normpath(os.path.join(root, "qtbase-everywhere-src-{}".format(qt_version)))
+        qtbase_url = "http://download.qt.io/official_releases/qt/{}/{}/submodules/qtbase-everywhere-src-{}.tar.xz".format(qt_short_version, qt_version, qt_version)
+        open("qtbase.tar.xz", "wb").write(requests.get(qtbase_url, allow_redirects=True).content)
+        execute_command("tar -xf qtbase.tar.xz")
+
+        os.chdir(qtbase_source_dir)
+
+        execute_command("chmod +x ./configure")
+        execute_command("./configure -opensource -confirm-license -prefix {} -no-opengl -nomake examples -nomake tests".format(qt_install_dir))
+        execute_command("make -j2")
+        execute_command("make install")
+
+        os.chdir(root)
+
+        qttools_source_dir  = os.path.normpath(os.path.join(root, "qttools-everywhere-src-{}".format(qt_version)))
+        qttools_url = "http://download.qt.io/official_releases/qt/{}/{}/submodules/qttools-everywhere-src-{}.tar.xz".format(qt_short_version, qt_version, qt_version)
+        open("qttools.tar.xz", "wb").write(requests.get(qttools_url, allow_redirects=True).content)
+        execute_command("tar -xf qttools.tar.xz")
+
+        os.chdir(qttools_source_dir)
+
+        execute_command("{}/bin/qmake qttools.pro".format(qt_install_dir))
+        execute_command("make -j2")
+        execute_command("make install")
+
+        os.chdir(repo)
+
     - name: Configure (Windows)
       if: ${{ matrix.config.name == 'Windows Latest MinGW64' }}
       shell: C:\\msys64\\msys2_shell.cmd -defterm -no-start -here -mingw64 -shell sh {0}
@@ -228,11 +283,12 @@ jobs:
         -D CMAKE_LINKER=/mingw64/bin/ld.exe \
         -D CMAKE_DLLTOOL=/mingw64/bin/dlltool.exe \
         -D CMAKE_NM=/mingw64/bin/nm.exe \
-        -D CMAKE_PREFIX_PATH=${{ env.ROOT_PATH }}\\${{ env.BOOST_INSTALL_PATH }} \
+        -D CMAKE_PREFIX_PATH=\
+        ${{ env.ROOT_PATH }}\\${{ env.BOOST_INSTALL_PATH }} \
         -D CMAKE_EXPORT_COMPILE_COMMANDS=ON
-        
-    - name: Configure (Ubuntu)
-      if: ${{ matrix.config.name == 'Ubuntu Latest GCC' }}
+
+    - name: Configure (Ubuntu & MacOS)
+      if: ${{ matrix.config.name == 'Ubuntu Latest Clang' || matrix.config.name == 'MacOS Latest Clang' }}
       env:
         CC: ${{ matrix.config.cc }}
         CXX: ${{ matrix.config.cxx }}
@@ -242,21 +298,10 @@ jobs:
         -B build \
         -D CMAKE_BUILD_TYPE=${{ matrix.config.build_type }} \
         -G Ninja \
-        -D CMAKE_PREFIX_PATH="${{ env.ROOT_PATH }}/${{ env.BOOST_INSTALL_PATH }};${{ env.ROOT_PATH }}/${{ env.CYRUS_SASL_INSTALL_PATH }}" \
-        -D CMAKE_EXPORT_COMPILE_COMMANDS=ON
-        
-    - name: Configure (MacOS)
-      if: ${{ matrix.config.name == 'MacOS Latest Clang' }}
-      env:
-        CC: ${{ matrix.config.cc }}
-        CXX: ${{ matrix.config.cxx }}
-      run: |
-        cmake \
-        -S . \
-        -B build \
-        -D CMAKE_BUILD_TYPE=${{ matrix.config.build_type }} \
-        -G Ninja \
-        -D CMAKE_PREFIX_PATH="${{ env.ROOT_PATH }}/${{ env.BOOST_INSTALL_PATH }};${{ env.ROOT_PATH }}/${{ env.CYRUS_SASL_INSTALL_PATH }};/usr/local/opt/qt" \
+        -D CMAKE_PREFIX_PATH=\
+        "${{ env.ROOT_PATH }}/${{ env.BOOST_INSTALL_PATH }};\
+        ${{ env.ROOT_PATH }}/${{ env.CYRUS_SASL_INSTALL_PATH }};\
+        ${{ env.ROOT_PATH }}/${{ env.QT_INSTALL_PATH }}" \
         -D CMAKE_EXPORT_COMPILE_COMMANDS=ON
 
     - name: Build
@@ -295,7 +340,7 @@ jobs:
         copy "C:\\msys64\\mingw64\\bin\\libbrotlicommon.dll"        install\\bin
         copy "C:\\msys64\\mingw64\\bin\\libiconv-2.dll"             install\\bin
         copy "C:\\msys64\\mingw64\\bin\\zlib1.dll"                  install\\bin
-    
+
     - name: Win Deploy Qt
       if: ${{ matrix.config.name == 'Windows Latest MinGW64' }}
       shell: C:\\msys64\\msys2_shell.cmd -defterm -no-start -here -mingw64 -shell sh {0}
@@ -307,46 +352,58 @@ jobs:
       with:
         path: ./install
         name: ${{ matrix.config.artifact }}
-        
+
     - name: Prepare to run static analysis (Ubuntu)
-      if: ${{ matrix.config.name == 'Ubuntu Latest GCC' }}
+      if: ${{ matrix.config.name == 'Ubuntu Latest Clang' }}
       run: mkdir reports
-        
+
     - name: Install clang-tidy (Ubuntu)
-      if: ${{ matrix.config.name == 'Ubuntu Latest GCC' }}
+      if: ${{ matrix.config.name == 'Ubuntu Latest Clang' }}
       run: sudo apt-get install clang-tidy -y
-        
+
     - name: Run clang-tidy (Ubuntu)
-      if: ${{ matrix.config.name == 'Ubuntu Latest GCC' }}
-      run: run-clang-tidy -p=build 2>&1 | tee reports/clang-tidy-report.log
+      if: ${{ matrix.config.name == 'Ubuntu Latest Clang' }}
+      run: run-clang-tidy -p=build -j=2 2>&1 | tee reports/clang-tidy-report.log
 
     - name: Install PVS-Studio (Ubuntu)
-      if: ${{ matrix.config.name == 'Ubuntu Latest GCC' }}
+      if: ${{ matrix.config.name == 'Ubuntu Latest Clang' }}
       shell: sh {0}
       run: |
         wget -q -O - https://files.viva64.com/etc/pubkey.txt | sudo apt-key add -
         sudo wget -O /etc/apt/sources.list.d/viva64.list https://files.viva64.com/etc/viva64.list
         sudo apt-get update
         sudo apt-get install pvs-studio
-      
+
     - name: Run PVS-Studio (Ubuntu)
-      if: ${{ matrix.config.name == 'Ubuntu Latest GCC' }}
+      if: ${{ matrix.config.name == 'Ubuntu Latest Clang' }}
       env:
         PVS_NAME: ${{ secrets.PVS_NAME }}
         PVS_KEY: ${{ secrets.PVS_KEY }}
       shell: sh {0}
       run: |
         pvs-studio-analyzer credentials $PVS_NAME $PVS_KEY
-        pvs-studio-analyzer analyze -f build/compile_commands.json
-        plog-converter -t fullhtml -o reports/pvs-report PVS-Studio.log
-        
+        pvs-studio-analyzer analyze -j2 -f build/compile_commands.json
+        plog-converter -t fullhtml -o reports/pvs-report -a GA:1,2,3 PVS-Studio.log
+
     - name: Upload static analysis results (Ubuntu)
-      if: ${{ matrix.config.name == 'Ubuntu Latest GCC' }}
+      if: ${{ matrix.config.name == 'Ubuntu Latest Clang' }}
       uses: actions/upload-artifact@v2
       with:
         path: ./reports
         name: static-analyzer-reports
-    
+
+    - name: Fail if clang-tidy found warnings
+      if: ${{ matrix.config.name == 'Ubuntu Latest Clang' }}
+      shell: sh {0}
+      run: |
+        cat reports/clang-tidy-report.log | grep -E 'warning: |error: '; status=$?; test $status -ne 0
+
+    - name: Fail if PVS-Studio found warnings
+      if: ${{ matrix.config.name == 'Ubuntu Latest Clang' }}
+      shell: sh {0}
+      run: |
+        plog-converter -t tasklist -a GA:1,2,3 -w PVS-Studio.log
+
   #release:
     #if: contains(github.ref, 'tags/v')
     #runs-on: ubuntu-latest
@@ -386,7 +443,7 @@ jobs:
             #os: ubuntu-latest
           #}
         #- {
-            #name: "Ubuntu Latest GCC", artifact: "Linux.tar.xz",
+            #name: "Ubuntu Latest Clang", artifact: "Linux.tar.xz",
             #os: ubuntu-latest
           #}
         #- {
