Downgrade clang-tidy 11 to 10

diff --git a/.github/workflows/linux-macos.yml b/.github/workflows/linux-macos.yml
--- a/.github/workflows/linux-macos.yml
+++ b/.github/workflows/linux-macos.yml
@@ -696,9 +696,10 @@ jobs:
     - name: Install clang-tidy
       if: ${{ matrix.config.suffix == 'clang-tidy' }}
       run: |
-        sudo apt install clang-tidy-11 -y
-        sudo update-alternatives --install /usr/bin/clang-tidy      clang-tidy      /usr/bin/clang-tidy-11 100
-        sudo update-alternatives --install /usr/bin/run-clang-tidy  run-clang-tidy  /usr/bin/run-clang-tidy-11 100
+        sudo apt install clang-tidy -y
+        #sudo apt install clang-tidy-11 -y
+        #sudo update-alternatives --install /usr/bin/clang-tidy      clang-tidy      /usr/bin/clang-tidy-11 100
+        #sudo update-alternatives --install /usr/bin/run-clang-tidy  run-clang-tidy  /usr/bin/run-clang-tidy-11 100
 
     - name: Run clang-tidy
       if: ${{ matrix.config.suffix == 'clang-tidy' }}
@@ -735,7 +736,7 @@ jobs:
       if: ${{ matrix.config.suffix == 'clang-tidy' }}
       shell: sh {0}
       run: |
-        cat reports/clang-tidy-report.log | grep -E 'warning: |error: ' | grep -v 'melon/build/src\|autogen'; status=$?; test $status -ne 0
+        cat reports/clang-tidy-report.log | grep -E 'warning: |error: ' | grep -v 'melon/build/src'; status=$?; test $status -ne 0
 
     - name: Fail if PVS-Studio found warnings
       if: ${{ matrix.config.suffix == 'PVS-Studio' }}
